### ISSUE TITLE
Time in  python

### ISSUE THREAD

**Issue by avsingh999** [avsingh999/Python-for-beginner#176]
how to print current time, time format conversion, and time delta in python

**Comment by Eshan2203** [comment]
I think it already have it https://docs.python.org/3/library/datetime.html#timezone-objects

What are you talking of ?

**Comment by avsingh999** [comment]
@Eshan2203 you can check now Ihave updated

**Comment by Eshan2203** [comment]
Ok I will take this ?

**Comment by Eshan2203** [comment]
In time format conversion, you want to convert date which is object to  datetime format ?

**Comment by avsingh999** [comment]
example: 04-10-2019 -> 10-04-2019 or 10/04/2019
:smile:

**Comment by avsingh999** [comment]
you can refer this link https://www.w3schools.com/python/python_datetime.asp

**Comment by Eshan2203** [comment]
Done I send you PR now
