### ISSUE TITLE
How to find if the number is odd or even in python

### ISSUE THREAD

**Issue by aaditpant** [avsingh999/Python-for-beginner#191]
a program to find if the given number is odd or even

**Comment by GabrielRato** [comment]
I can pick this

**Comment by krobitaille93** [comment]
I was trying to work on this but when I used the 'git push origin' command it said: 
"
remote: Permission to avsingh999/Python-for-beginner.git denied to krobitaille93. 
fatal: unable to access 'https://github.com/avsingh999/Python-for-beginner.git/': The requested URL return error: 403
"
