### ISSUE TITLE
update readme.md file 

### ISSUE THREAD

**Issue by avsingh999** [avsingh999/Python-for-beginner#210]
add newly added files in readme

**Comment by shiv-1998** [comment]
Hey! Can I work on this issue?

**Comment by achoudh5** [comment]
@avsingh999 would you like to clean up a bit, maybe make folders for loops, file handlers etc. ?
It is a long drag :P

**Comment by avsingh999** [comment]
@achoudh5 yes, I want only when someone sees and then he understands

**Comment by shiv-1998** [comment]
> @avsingh999 would you like to clean up a bit, maybe make folders for loops, file handlers etc. ?
> It is a long drag :P

Sure!
But it will require some time.

**Comment by avsingh999** [comment]
Np :smile:
