### ISSUE TITLE
print english char A pattern by input in python

### ISSUE THREAD

**Issue by avsingh999** [avsingh999/Python-for-beginner#231]

**Comment by shin-iji** [comment]
![image](https://user-images.githubusercontent.com/50923330/66291244-89f5a500-e90b-11e9-906d-a2201cd99aa7.png)

I write a code that can print English char A pattern. But I still confuse about _'by input'_. Can you describe to me more about this? Thanks!

**Comment by avsingh999** [comment]
If user will enter number then print only exact that row of star 
ex 
5
******
*      *
******
*     *
*     *

7
******
*     *
*     *
******
*     *
*     *
*     *
