### ISSUE TITLE
Check number is prime or not Optimization Solution

### ISSUE THREAD

**Issue by avsingh999** [avsingh999/Python-for-beginner#273]
There is already an Exist check Prime Number. But not optimize so Please add some optimize the solution for this

References: https://www.geeksforgeeks.org/c-program-to-check-prime-number/

**Comment by atyachari** [comment]
hey @avsingh999 can this be assigned to me?

**Comment by SardulDhyani** [comment]
Hi, @avsingh999 Please assign this issue to me.
Happy Hacktoberfest 🥳🥳

**Comment by avsingh999** [comment]
@SardulDhyani  Sorry First Come First .....

I will create another and assign to you 😄

**Comment by SardulDhyani** [comment]
@avsingh999 Thanks, man.

**Comment by atyachari** [comment]
Thanks @avsingh999.
Here is the PR https://github.com/avsingh999/Python-for-beginner/pull/275
