### ISSUE TITLE
substring of string in python

### ISSUE THREAD

**Issue by avsingh999** [avsingh999/Python-for-beginner#29]
#### create .md file name should be a title of the issue
:heart:
Thank you

**Comment by Haadia** [comment]
I'll work on this one.

**Comment by avsingh999** [comment]
@Haadia  Great Go ahead

**Comment by chiru091096** [comment]
@Haadia, @avsingh999 
if nobody is working on this issue , can I work on it?

**Comment by avsingh999** [comment]
@chiru091096 sorry, already pr and has been merged
thanks for your interest
