### ISSUE TITLE
simple gui in tkinter python?

### ISSUE THREAD

**Issue by avsingh999** [avsingh999/Python-for-beginner#77]
#### create .md file name should be a title of the issue
:heart:
Thank you

**Comment by a96tudor** [comment]
hey! I'd like to work on this. Is there anything specific you want to see in the GUI?

**Comment by avsingh999** [comment]
@a96tudor great, there is not specific you have to add button, and action  onClick
anything info you can add about Tkinter, 
thank you for interest
😃
