### ISSUE TITLE
insertion sort in python

### ISSUE THREAD

**Issue by avsingh999** [avsingh999/Python-for-beginner#89]
### file name should be a name of algorithm
Thank you
:heart::heart::heart::heart:

**Comment by ajespoo** [comment]
Insertion sort is a simple sorting algorithm that works the way we sort playing cards in our hands.
Algorithm
// Sort an arr[] of size n
insertion Sort(arr, n)
Loop from i = 1 to n-1.
……a) Pick element arr[i] and insert it into sorted sequence arr[0…i-1]
