### ISSUE TITLE
heap sort in python

### ISSUE THREAD

**Issue by avsingh999** [avsingh999/Python-for-beginner#91]
### file name should be a name of algorithm
Thank you
:heart::heart::heart::heart:

**Comment by ajespoo** [comment]
1. Build a max heap from the input data.
2. At this point, the largest item is stored at the root of the heap. Replace it with the last item of the heap followed by reducing the size of heap by 1. Finally, heapify the root of tree.
3. Repeat above steps while size of heap is greater than 1.

How to build the heap?
Heapify procedure can be applied to a node only if its children nodes are heapified. So the heapification must be performed in the bottom up order.
