### ISSUE TITLE
quicksort algorithm in pyhton

### ISSUE THREAD

**Issue by avsingh999** [avsingh999/Python-for-beginner#92]
### file name should be algorithm name
:heart: :heart: 
thnak you

**Comment by susantruong** [comment]
@avsingh999 I am new with python language, so I want to try this issue to learn about python. Would you please assign it to me?

**Comment by OrestJano** [comment]
I`m on it sign me up

**Comment by avsingh999** [comment]
@susantruong  go ahead
thanks :)

**Comment by avsingh999** [comment]
@OrestJano sorry first come first service you can take another issue
thanks :)
